version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todo-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./hw-todo/src/app"
    networks:
      - app-tier
    depends_on:
      - pgsqldb
  pgsqldb:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data